### ISSUE TITLE
提示版本过低

### ISSUE THREAD

**Issue by Ca11back** [eatmoreapple/wxhelper#28]
![Screenshot from 2024-08-28 22-02-55](https://github.com/user-attachments/assets/ba9b87b6-7653-463b-8e0f-e6458ff50a57)

**Comment by caicai618** [comment]
我也是提示浏览器版本过低，你有解决办法吗

**Comment by Ca11back** [comment]
> 我也是提示浏览器版本过低，你有解决办法吗

已改用wechatferry，或者可以找一个hook解决此问题（见过但没用过，请自行查找）
